language: node_js

node_js:
  - "4.2"
  - "4.1"
  - "4.0"

os: osx

before_install:
  - brew update
  - brew upgrade --all

install: brew install node
before_script: npm install -g grunt-cli electron-packager
script: grunt darwin
