language: objective-c

os: osx

install:
  - bash install_identity.sh
  - npm install
  - npm install -g grunt-cli electron-packager appdmg

script: grunt darwin

addons:
  artifacts:
    paths:
      - $(ls build/release/*/* | tr "\n" ":")
