language: objective-c

os: osx

install:
  - bash install_identity.sh
  - npm install
  - npm install -g grunt-cli electron-packager appdmg

script: grunt darwin

before_deploy:
  - export DMG_RELEASE=$(ls build/release/*/*.dmg)
  - export ZIP_RELEASE=$(ls build/release/*/*.zip)

addons:
  artifacts:
    paths:
      - $(ls build/release/*/* | tr "\n" ":")
