language: objective-c

os: osx

install:
  - security import resource/cert.p12 -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
  - npm install
  - npm install -g grunt-cli electron-packager

script: grunt darwin
